language: php
php:
  - 7

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - source

before_script:
  - gem install sass
  - composer self-update
  - composer install --prefer-dist

script:
  - sh publish.sh

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi
